apiVersion: v1alpha1
kind: Setting
metadata:
  name: wedding-setting
spec:
  forms:
    # =====================
    # 基础设置
    # =====================
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: text
          id: groomName
          name: groomName
          label: 新郎姓名
          placeholder: 请输入新郎姓名
          value: 朱迪
          validation: required
        - $formkit: text
          id: brideName
          name: brideName
          label: 新娘姓名
          placeholder: 请输入新娘姓名
          value: 小梅
          validation: required
        - $formkit: datetime-local
          id: weddingDate
          name: weddingDate
          label: 婚期（阳历）
          value: "2026-10-01 12:00"
          validation: required
        - $formkit: text
          id: chineseWeddingDate
          name: chineseWeddingDate
          label: 婚期（农历）
          value: "农历二〇二六年 十月初一"
          validation: required
        - $formkit: text
          id: cityName
          name: cityName
          label: 城市名称
          placeholder: 请输入城市名称
          value: 上海
          validation: required
        - $formkit: text
          id: weddingLocation
          name: weddingLocation
          label: 婚礼地点
          placeholder: 请输入婚礼地点
          value: 上海·外滩茂悦酒店
          validation: required
        - $formkit: attachment
          id: backMusic
          name: backMusic
          label: 背景音乐
          value: "https://img.aiym.fun:8888/halo/M500002z7S8T0JoS9W.mp3"
          placeholder: 请输入背景音乐URL或者选择附件中音乐
        - $formkit: attachment
          id: posterUrl
          name: posterUrl
          label: 海报
          value: ""
          placeholder: 请输入背景海报URL或者选择附件中图片
        - $formkit: text
          id: welcomeDesc
          name: welcomeDesc
          label: 海报描述
          value: "良辰已至，喜宴将开"
          placeholder: 请输入海报下方欢迎描述
        - $formkit: text
          id: remind
          name: remind
          label: 温馨提醒
          value: "期待您的到来"
          placeholder: 请输入海报下方欢迎描述
        - $formkit: text
          id: mapLocation
          name: mapLocation
          label: 地图位置（经度,纬度）
          placeholder: "例如: 121.488585,31.240801"
          value: ""
        - $formkit: radio
          id: enableWeather
          name: enableWeather
          label: 启用天气显示
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
          help: 启用天气显示功能，会在页面顶部显示实时天气信息，天气城市为设置的城市天气。

    # =====================
    # 流程节点配置
    # =====================
    - group: timeline
      id: timeline
      name: timeline
      label: 流程节点配置
      formSchema:
        - $formkit: repeater
          id: timelineNodes
          name: timelineNodes
          max: 10
          label: 流程列表
          value:
            - title: "接亲出发"
              description: "前往新娘家接亲"
              type: "timepoint"
              startTime: "06:30"
            - title: "婚礼仪式"
              description: "正式举行婚礼仪式"
              type: "timespan"
              startTime: "11:30"
              endTime: "12:00"
          children:
            - $formkit: text
              id: title
              name: title
              label: 节点标题
            - $formkit: textarea
              id: description
              name: description
              label: 节点描述
            - $formkit: select
              id: type
              name: type
              label: 节点类型
              value: timepoint
              options:
                - label: 时间点
                  value: timepoint
                - label: 时间段
                  value: timespan
            - $formkit: time
              id: startTime
              name: startTime
              label: 开始时间
            - $formkit: time
              if: '$node.value.type == "timespan"'
              id: endTime
              name: endTime
              label: 结束时间

    # =====================
    # 相册配置
    # =====================
    - group: album
      label: 相册配置
      formSchema:
        - $formkit: select
          id: galleryName
          name: galleryName
          key: galleryName
          label: 相册展示图库
          multiple: true
          clearable: true
          action: /apis/console.api.photo.halo.run/v1alpha1/photogroups
          requestOption:
            method: GET
            pageField: page
            sizeField: size
            totalField: total
            itemsField: items
            labelField: spec.displayName
            valueField: metadata.name
          help: 建议上传婚纱照到图库（相册基于图库插件实现，需要先安装图库管理插件并配置图库相册信息，插件地址：https://www.halo.run/store/apps/app-BmQJW）
        - $formkit: select
          id: displayMode
          name: displayMode
          label: 展示模式
          value: heart
          options:
            - label: 爱心模式
              value: heart
            - label: 胶卷模式
              value: film
            - label: 杂志模式
              value: magazine
        - $formkit: number
          id: pageSize
          name: pageSize
          label: 每页显示数量
          value: 10

    # =====================
    # 歌单配置
    # =====================
    - group: aplayer
      label: 歌单配置
      formSchema:
        - $formkit: text
          id: host
          name: host
          label: Meting API 地址
          value: https://api.injahow.cn/meting/
          help: 支持 Meting 类型格式的 API，不保证 API 可用度，如无法使用请自行搭建。 https://github.com/injahow/meting-api
        - $formkit: select
          id: server
          name: server
          label: 音乐服务商
          help: 不同接口所支持的音乐服务商不同，如无法使用请自行更换
          value: netease
          options:
            - value: netease
              label: 网易云音乐
            - value: tencent
              label: QQ 音乐
            - value: xiami
              label: 虾米音乐
            - value: kugou
              label: 酷狗音乐
            - value: baidu
              label: 百度音乐
        - $formkit: select
          id: type
          name: type
          label: 类别
          value: playlist
          options:
            - value: song
              label: 单曲
            - value: playlist
              label: 歌单
            - value: album
              label: 专辑
            - value: artist
              label: 歌手
            - value: search
              label: 搜索
        - $formkit: text
          id: id
          name: id
          label: id
          value: 14425394622
        - $formkit: select
          id: preload
          name: preload
          label: 预加载
          value: none
          options:
            - value: none
              label: 无
            - value: metadata
              label: 仅元数据
            - value: auto
              label: 自动
        - $formkit: number
          id: volume
          name: volume
          label: 默认音量大小
          value: 0.7
        - $formkit: checkbox
          name: autoplay
          label: 自动播放
          value: false
          help: 由于浏览器限制，此功能可能无法生效！（也建议不要开启，会产生噪音，影响用户体验）
        - $formkit: select
          id: order
          name: order
          label: 播放顺序
          value: random
          options:
            - value: list
              label: 列表
            - value: random
              label: 随机
        - $formkit: color
          id: theme
          name: theme
          label: 主题色
          value: "#FFA500"

    # =====================
    # 主题配置
    # =====================
    - group: theme
      label: 主题配置
      formSchema:
        - $formkit: group
          id: colors
          name: colors
          label: 主题颜色
          children:
            - $formkit: color
              id: primary
              name: primary
              label: 主色调
              value: "#d43f3a"
              help: "主色：按钮、高亮、图标"
            - $formkit: color
              id: secondary
              name: secondary
              label: 次色调
              value: "#ff9a9e"
              help: "渐变尾部、柔和背景"
        - $formkit: group
          id: fonts
          name: fonts
          label: 字体设置
          children:
            - $formkit: text
              id: main
              name: main
              label: 主字体
              value: serif
        - $formkit: textarea
          id: customCss
          name: customCss
          label: 自定义 CSS
          value: ""